name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.101.0
        HUGO_EXTENDED: true
        TARGET_REPO: saptam04/academic-website
        TARGET_BRANCH: gh-pages
        TOKEN: ${{ secrets.MY_SECRET }}
        HUGO_ARGS: --debug
        GO_VERSION: 1.18.3